source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0.preview2'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "7.1.0"

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '6.4.0'

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# PostgreSQL
gem "pg"

# Use Redis adapter to run Action Cable in production
gem "redis"

# redis-rails
gem "redis-rails"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors"

# Environment
gem "dotenv-rails"

# flexible and safe downloading of remote files
gem "down"

# draper
gem "draper"

# Sidekiq
gem "sidekiq"

# taglib-ruby
gem "taglib-ruby"
